adding support for SRV records
mnezerka/dnslib pull request #10
Opened 2021-10-20 11:07 UTC by reuven8e14

2021-10-20 12:57 UTC, mnezerka requested changes
Thanks. Could you address my findings, please? I'll then merge it.

2021-10-20 12:57 UTC, mnezerka commented on src/rr.h
> +        virtual eRDataType getType() const { return RDATA_SRV; };
Could you remove `const` please? It hides overloaded virtual function, which has different qualifiers (unqualified vs 'const'):
```
virtual eRDataType getType() = 0;
```

2021-10-20 12:57 UTC, mnezerka commented on src/unittests.cpp
> +    assert (r.getType(), dns::RDATA_SRV);
Not sure if you tried to test it, but assert takes one argument (expression) and verifies the result of the expression. At least on my MacBook, where I tried to verify your PR. Could you change it from `,` to `==`, please? Same on following lines in this test function body.

2021-10-20 13:06 UTC, reuven8e14 commented on src/rr.h
> +        virtual eRDataType getType() const { return RDATA_SRV; };
yup, sure np.

2021-10-20 13:07 UTC, reuven8e14 commented on src/unittests.cpp
> +    assert (r.getType(), dns::RDATA_SRV);
correct, my mistake forgot to change from our macros check.

2021-10-20 13:33 UTC, mnezerka approved these changes
Looks good. Thank you very much for your participation!

2021-10-20 13:34 UTC, merged

2022-05-21 07:51 UTC, wxiaoguang commented on src/rr.cpp
> +    mTarget.pop_back();
hint: the `target` is a domain-name, should be read by `buffer.getDnsDomainName`.

And `mTarget.pop_back();` might cause segfault when processing corrupted message.

2022-05-26 11:24 UTC, mnezerka commented on src/rr.cpp
> +    mTarget.pop_back();
Can you write a unit test that triggers this?

2022-05-26 12:05 UTC, wxiaoguang commented on src/rr.cpp
> +    mTarget.pop_back();
I didn't use this code, I am using `getDnsDomainName` already.

To trigger the case, make a SRV record with an empty domain field, then the `while` won't be executed, then mTarget is empty, then `mTarget.pop_back()` will crash. https://en.cppreference.com/w/cpp/string/basic_string/pop_back : The behavior is undefined if the string is empty.