Fix set save pos at end
mnezerka/dnslib pull request #12
Opened 2023-01-17 02:47 UTC by piz-ewing

fix #5

2023-01-18 07:05 UTC, mnezerka requested changes
Thank you for your work. I appreciate it. Could you address my comments please? Thank you.

2023-01-18 07:05 UTC, mnezerka commented on src/buffer.cpp
> +void Buffer::setSavePos(const uint pos)
I'm a bit lost. Why did you introduced completely new function instead of fixing existing `setPos`? Or do we need both? I understand that it is about last byte of the buffer, but having two variants of the same methods looks strange to me.

2023-01-18 07:05 UTC, mnezerka commented on src/rr.h
> +
Can you put this "Windows compatibility" changes into separate commit, please? I prefer isolation of features in separate commits to make it easy to manipulate with features (e.g. cherry picking, rollback, etc.) as well as transparent history of the project. Thank you.

2023-01-18 07:05 UTC, mnezerka commented on src/rr.h
> +        eRDataType getType() const { return mType; };
Nice catch. Could you put fixing all those getters into separate commit, please? Explained above. It would be great to add also some simple unit test covering all those getters. I'll appreciate if you add some. Thank you.

2023-01-28 01:20 UTC, piz-ewing commented on src/buffer.cpp
> +void Buffer::setSavePos(const uint pos)
Because the parameter of setSavePos comes from the return value of getPos, it is safer.can also add a parameter to the original function to mark whether the parameter is safe.

2023-02-25 08:03 UTC, mnezerka requested changes
Hi, sorry for delayed review. I was ill for a long time. Check my findings, please. Thank you for your work.

2023-02-25 08:03 UTC, mnezerka commented on src/unittests.cpp
> +            std::snprintf(ip.data(), ip.capacity(), "%d.%d.%d.%d", addr[0], addr[1], addr[2], addr[3]);
I couldn't build your code (Ubuntu 20.04):
```
 error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
  371 |             std::snprintf(ip.data(), ip.capacity(), "%d.%d.%d.%d", addr[0], addr[1], addr[2], addr[3]);
      |                           ~~~~~~~^~
      |                                  |
      |                                  const char*
```

2023-02-25 08:03 UTC, mnezerka commented on src/buffer.cpp
> +    if (pos > mBufferSize || (pos == mBufferSize && !saved))
It would be great to add documentation (doc string) for this method explaining difference between calls with saved set to true or false. The word `saved` doesn't say too much and will cause users to study the code. And unfortunatelly, it is not clear also from code itself. If you formulate it in a simple and clear way, it would be great.

BTW: Would it be a problem do get rid of this parameter and rather change this method to following?
```
void Buffer::setPos(const uint pos)
    if (pos > mBufferSize)
        throw(Exception("Try to set pos behind buffer"));
    mBufferPtr = mBuffer + pos;
}
```

2023-02-27 04:02 UTC, piz-ewing commented on src/buffer.cpp
> +    if (pos > mBufferSize || (pos == mBufferSize && !saved))
I'm sorry to hear that.After `setPos` is called, maybe `BufferPtr` will be used. If it is changed to `pos > BufferSize`, there will be security issues.

2023-02-27 06:51 UTC, mnezerka commented on src/buffer.cpp
> +    if (pos > mBufferSize || (pos == mBufferSize && !saved))
What do you mean by "security" issues? Any example?

2023-02-27 07:05 UTC, piz-ewing commented on src/buffer.cpp
> +    if (pos > mBufferSize || (pos == mBufferSize && !saved))
I believe that there is a risk of improper use, and therefore, it is not advisable to set the 'pos' to an unavailable location. Doing so would only defer the error to 'checkAvailableSpace', which may not be an ideal solution.

2023-02-27 07:13 UTC, piz-ewing commented on src/buffer.cpp
> +    if (pos > mBufferSize || (pos == mBufferSize && !saved))
if you insist, I can do it this way.👀

2023-02-27 07:18 UTC, piz-ewing commented on src/buffer.cpp
> +    if (pos > mBufferSize || (pos == mBufferSize && !saved))
example A: if (pos >= mBufferSize)
```
setPos(posEnd);  // panic here
// ...
// ...
getBytes(1);
```

example B: if (pos > mBufferSize)
```
setPos(posEnd);
// ...
// ...
getBytes(1); // panic here
```

2023-02-27 07:40 UTC, piz-ewing commented on src/unittests.cpp
> +            std::snprintf(ip.data(), ip.capacity(), "%d.%d.%d.%d", addr[0], addr[1], addr[2], addr[3]);
I have tested it on Arch Linux, Ubuntu 20.04, and Windows 10.

2023-09-15 01:15 UTC, closed without merging